config/routes.rb
Rails.application.routes.draw do
  get '/edit' => 'articles#edit'
  resources :articles
  root 'articles#index'
  get '/signup' => 'users#new'
  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/profile' => 'users#show'
  get '/profile/:id/edit' => 'users#edit', as: :user_edit
  patch '/profile/:id' => 'users#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  def author?
    self.role == 'author'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user # Строка helper_method: current_user делает метод current_user доступным во вьюхах.

  def current_user # Метод current_user определяет, вошел ли пользователь в систему или вышел из нее. Это делается путем проверки наличия пользователя в базе данных с данным идентификатором сеанса. Если есть, это означает, что пользователь вошел в систему, и @current_user сохранит этого пользователя; в противном случае пользователь вышел из системы, и @current_user будет иметь значение nil.
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user # Метод require_user использует метод current_user для перенаправления вышедших из системы пользователей на страницу входа.
    redirect_to '/login' unless current_user
  end

  def login_user_to_index
    redirect_to '/' if current_user
  end

  def require_author # Аналогично метод require_author должен использовать метод current_user, чтобы проверить, является ли пользователь автором, и перенаправить на корневой путь, если он / она не является.
    redirect_to '/' unless current_user.author?
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


    before_action :require_user, except: [:index] # требовать, чтобы пользователи входили в систему для всех действий, кроме действия индекса. тут мы решаем проблему при которой для просмотра индивидуальных статей пользователь должен быть залогинен. Метод require_user мы создаем в application_controller

    before_action :require_author, only: [:edit, :update, :destroy]

    def index
      @articles = Article.all
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to articles_path
    end

    private
    def article_params
      params.require(:article).permit(:title, :author, :body)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :login_user_to_index, except: [:destroy]

  def new

  end

  def create # тут обрабатываем входящий пост запрос при авторизации пользователя. Находим юзера по email. Если находим, то ридерктим на главную страницу. В противном случае редиректим на /login
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy # тут мы обрабатываем delete запрос, когда пользователь делает logout. Путём установки хёша сессии пользователя в nil и последующим редиректом в root дерикторию
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :login_user_to_index, except: [:show, :edit, :update]
   before_action :require_user, except: [:new] # Выдавать неавторизованному пользователю страницу с логином, исключение переход на страницу с регистрацией. Делаю это для того чтобы не падала ошибка при попытке неавторизаванного пользователя перейти по ссылке /profile (в контроллере метод show)

  def new
    @user = User.new
  end
  private def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

   def show
     @user = User.find(session[:user_id])
   end

   def update
     @user = User.find(session[:user_id])
     if @user.update_attributes(user_params)
       redirect_to(:action => 'show', :id => @user.id)
       else render 'edit'
     end
   end

   def edit
     @user = User.find(session[:user_id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="update-article">
  <div class="container">

    <%= form_for(@article) do |f| %>
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_area :body %>

      <%= f.submit "Save", :class => "btn-submit" %>
    <% end %>

  </div>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <div class="container">

    <%= @articles.each do |article| %>
      <div class="article">
        <p class="date"><%= article.created_at.strftime('%b %d') %></p>
        <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
        <%= link_to(article) do %>
          <h2><%= article.title %></h2>
        <% end %>
        <p class="author">by <%= article.author %></p>
        <p class="article_content"><%= truncate(article.body , :length => 140) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new-article">
  <div class="container">

    <%= form_for(@article) do |f| %>
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_area :body %>

      <%= f.submit "Save" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article">
  <div class="container">
    <p class="date"><%= @article.created_at.strftime('%b %d') %></p>
    <h2><%= @article.title %></h2>
    <p class="author">by <%= @article.author %></p>
    <p class="article_content"><%= @article.body %></p>

    <% if current_user && current_user.author? %>
      <p class="article-edit">
        <%= link_to "Edit Article", edit_article_path(@article.id) %>
      </p>
      <p class="article-delete">
        <%= link_to "Delete Article", article_path(@article), method: "delete" %>
      </p>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newstand</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,100,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <%= link_to(root_path) do %>
      <h1><span class="dark">n</span>ewstand</h1>
    <% end %>

    <div class="nav">
      <% if current_user %> <!-- Если пользователь вошел в систему, показать адрес электронной почты пользователя и ссылку «Logout» -->
        <ul>
          <li><%= current_user.email %></li>
          <li><%= link_to "Profile", profile_path, method: "get" %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        </ul>
      <% else %> <!--Если пользователь вышел из системы, отобразите ссылку «Зарегистрироваться» и ссылку «Войти». -->
        <ul>
          <li><%= link_to "Login", 'login' %></li>
          <li><%= link_to "Signup", 'signup' %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>


<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<div class="user">
  <div class="container">
    <%= form_for(@user) do |u|%>
      <div class="field">
        <%=u.text_field :first_name %>
        <%=u.text_field :last_name %>
        <%=u.email_field :email %>
        <%=u.password_field :password %>
      </div>
      <div class="action">
        <%= u.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup">
  <div class="container">

    <!-- Your form here -->
    <%= form_for(@user) do |f| %>
      <div class="field">
        <%= f.text_field  :first_name %>
        <%= f.text_field  :last_name %>
        <%= f.email_field  :email %>
        <%= f.password_field  :password %>
      </div>
      <div class="actions">
        <%= f.submit "Create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
  <div class="container">
    <h2><%= @user.first_name %></h2>
    <h2><%= @user.last_name %></h2>
    <h2><%= @user.email %></h2>
    <%= link_to "Edit", user_edit_path(@user) %>
  </div>
</div>